# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/geode-experimental-driver"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/geode-protobuf/geode-protobuf-test"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/geode-protobuf"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/geode-protobuf-messages"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/buildSrc/src/main/groovy/org/apache/geode/gradle/plugins"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/buildSrc"
    schedule:
      interval: "daily"