name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.1
      - name: build (unix)
        run: ./gradlew build
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      - name: build (windows)
        run: ./gradlew.bat build -x spotlessCheck
        if: matrix.os == 'windows-latest'
  distributedTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.1
      - name: distributedTest (unix)
        run: ./gradlew distributedTest
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      - name: distributedTest (windows)
        run: ./gradlew.bat distributedTest
        if: matrix.os == 'windows-latest'
  integrationTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.0.1
      - name: integrationTest (unix)
        run: ./gradlew integrationTest
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
      - name: integrationTest (windows)
        run: ./gradlew.bat integrationTest
        if: matrix.os == 'windows-latest'
